<a href="https://colab.research.google.com/github/Maniacravi/pytorch-deep-learning/blob/main/00_pytorch_fundamentals_mani.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

My code along for the first section

## Import statements


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Tensors

### Intro

#### Scalars

In [2]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

9

In [5]:
scalar.shape

torch.Size([])

#### Vectors

In [6]:
vector = torch.tensor([9, 9, 9])
vector

tensor([9, 9, 9])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

#### MATRIX

In [9]:
MATRIX = torch.tensor([[9, 9],
                       [10, 11]])
MATRIX

tensor([[ 9,  9],
        [10, 11]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# slicing

MATRIX[0]

tensor([9, 9])

In [13]:
MATRIX[1, 0]

tensor(10)

#### TENSOR

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Creating Tensors

#### Random Tensors

Creating random tensors because they are the most usual way to create tensors in code

In [27]:
# Create a random tensor

random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.5634, 0.0523, 0.0011, 0.1825],
        [0.2674, 0.8673, 0.2341, 0.0161],
        [0.0299, 0.1540, 0.9526, 0.9091]])

In [19]:
random_tensor.shape

torch.Size([3, 4, 6])

In [20]:
random_tensor.ndim

3

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor, random_image_size_tensor.ndim, random_image_size_tensor.shape

(tensor([[[0.6763, 0.8986, 0.0291,  ..., 0.3638, 0.4245, 0.2210],
          [0.4569, 0.9883, 0.9402,  ..., 0.3334, 0.0104, 0.4459],
          [0.8517, 0.6790, 0.8334,  ..., 0.4194, 0.8088, 0.4164],
          ...,
          [0.5148, 0.9991, 0.8305,  ..., 0.1391, 0.7130, 0.7386],
          [0.8243, 0.9806, 0.4165,  ..., 0.8762, 0.3138, 0.4268],
          [0.0014, 0.4376, 0.7164,  ..., 0.8895, 0.8005, 0.6523]],
 
         [[0.8994, 0.2043, 0.3196,  ..., 0.9814, 0.1752, 0.1710],
          [0.7753, 0.1107, 0.0546,  ..., 0.6809, 0.6535, 0.7321],
          [0.4655, 0.9326, 0.4491,  ..., 0.8731, 0.6571, 0.5260],
          ...,
          [0.1811, 0.0299, 0.0948,  ..., 0.2943, 0.6694, 0.5973],
          [0.2277, 0.2890, 0.6889,  ..., 0.1274, 0.9975, 0.5521],
          [0.3556, 0.0566, 0.2336,  ..., 0.3565, 0.2408, 0.5647]],
 
         [[0.7334, 0.2408, 0.6974,  ..., 0.6584, 0.2214, 0.2447],
          [0.0364, 0.3451, 0.2567,  ..., 0.2909, 0.0730, 0.0357],
          [0.1354, 0.3560, 0.4792,  ...,

In [24]:
# Create a random tensor again
random_tensor_2 = torch.rand(size=(3, 1920, 1080))
random_tensor_2.shape

torch.Size([3, 1920, 1080])

#### Zeros and Ones

In [25]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# All ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype # Explore the datatype of the tensor

torch.float32

#### Creating a Range of tensors and tensors-like

In [35]:
# torch.range
torch.range(0,10) # Deprecated

<ipython-input-35-462832172>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# also can use step
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [40]:
# Create tensors like
ten_zeros = torch.zeros_like(input = one_to_ten) # Returns a tensor filled with the scalar value 0, with the same size as input
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [41]:
# Float_32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None) # What datatype is the tensor


In [42]:
float_32_tensor.dtype

torch.float32

Even when dtype is specified as None - still produces a float32 tensor

In [43]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor
                               device=None, # What device is your tensor on ('cpu', 'gpu' etc)
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

** Note ** : Learn about tensor datatypes and their differences. May run into errors with this often

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16) # Crearting a float16 tensor from the float32 tensor
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

This works surprisignly but beware of mixing multiple types of tensors. Sometimes will raise errors

In [47]:
int_32_tensor = float_32_tensor.type(dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [48]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

Still works

#### Getting info from Tensors

In [49]:
# Get dtype
int_32_tensor.dtype

torch.int32

In [50]:
# Get shape
float_32_tensor.shape

torch.Size([3])

In [51]:
# Get device
float_16_tensor.device

device(type='cpu')

In [52]:
# Get ndim
int_32_tensor.ndim

1

#### Manipulating Tensors (tensor operations)

Includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Mat Mult

In [53]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [54]:
# Add two tensors
int_32_tensor + float_32_tensor

tensor([ 6., 12., 18.])

In [55]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [56]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [59]:
# Torch inbuilt functions
torch.mul(tensor, 10), torch.add(tensor, 10), torch.sub(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]), tensor([-9, -8, -7]))

#### Matrix multiplication

In [64]:
# Mat mult
torch.matmul(float_32_tensor, tensor.type(torch.float32))

tensor(42.)

In [68]:
# Another one
torch.matmul(torch.rand(size=(4,4)), torch.rand(size=(4,1)))

tensor([[0.9462],
        [1.0132],
        [1.3153],
        [0.6183]])

In [71]:
# Do the matmul by forloop and see how long the time difference is
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value


CPU times: user 856 µs, sys: 1 ms, total: 1.86 ms
Wall time: 1.57 ms


tensor(14)

In [72]:
# same using matmul
%%time
torch.matmul(tensor, tensor) # Vectorized version - therefore much faster


CPU times: user 537 µs, sys: 0 ns, total: 537 µs
Wall time: 381 µs


tensor(14)

In [73]:
# One of the common errors is a size mismacth error

tensor_A = torch.rand(size=(5,4))
torch.mm(tensor_A, tensor_A) # torch.mm is an alias for torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x4 and 5x4)

In [74]:
# Transpose - we need to transpose the matrix for this to work
torch.mm(tensor_A, tensor_A.T)

tensor([[0.5776, 0.9577, 0.8314, 1.1441, 0.8169],
        [0.9577, 1.7332, 1.3044, 1.8969, 1.3723],
        [0.8314, 1.3044, 1.5490, 1.7922, 1.2438],
        [1.1441, 1.8969, 1.7922, 2.3343, 1.6562],
        [0.8169, 1.3723, 1.2438, 1.6562, 1.1825]])

In [76]:
tensor_B = torch.rand(size=(5, 4))
tensor_B

tensor([[0.1893, 0.9947, 0.0561, 0.2517],
        [0.4527, 0.4505, 0.8271, 0.5013],
        [0.6903, 0.6950, 0.2834, 0.5624],
        [0.2428, 0.1631, 0.5228, 0.7988],
        [0.4157, 0.8759, 0.8528, 0.4749]])

In [77]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([5, 4]), tensor_B = torch.Size([5, 4])

New shapes: tensor_A = torch.Size([5, 4]) (same as above), tensor_B.T = torch.Size([4, 5])

Multiplying: torch.Size([5, 4]) * torch.Size([4, 5]) <- inner dimensions match

Output:

tensor([[0.4587, 0.7956, 0.8279, 0.6919, 0.8745],
        [0.5520, 1.3379, 1.3177, 1.0910, 1.3759],
        [1.0370, 1.3779, 1.3339, 0.9972, 1.7030],
        [1.0192, 1.6956, 1.6819, 1.3700, 1.9225],
        [0.6548, 1.2057, 1.1665, 0.9945, 1.3331]])

Output shape: torch.Size([5, 5])


#### Aggregation (min, max, mean, sum)

In [80]:
# Create a tensor
x = torch.arange(-50, 64, step=0.1)
x.shape

torch.Size([1140])

In [82]:
# min
torch.min(x), x.min() # Same

(tensor(-50.), tensor(-50.))

In [83]:
# max
x.max()

tensor(63.9000)

In [84]:
# mean
x.mean()

tensor(6.9500)

In [86]:
# median
x.median()

tensor(6.9000)

In [87]:
# sum
torch.sum(x)

tensor(7923.)

In [89]:
# argmax and argmin
print(f'argmax: {x.argmax()} | x[argmax]: {x[x.argmax()]}')
print(f'argmin: {x.argmin()} | x[argmin]: {x[x.argmin()]}')

argmax: 1139 | x[argmax]: 63.900001525878906
argmin: 0 | x[argmin]: -50.0


#### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

In [92]:
# Create a tensor
x = torch.arange(1., 8.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), 1)

In [93]:
# Reshape
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [100]:
# View
z = x.view(7,1)
z

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])

In [105]:
z[4,0] = 10
z, x

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [10.],
         [ 6.],
         [ 7.]]),
 tensor([ 1.,  2.,  3.,  4., 10.,  6.,  7.]))

This changed both z and x since z is a view of x (shares memory)

In [107]:
# Stack

x_vstacked = torch.stack([x, x, x, x], dim=0)
x_vstacked

tensor([[ 1.,  2.,  3.,  4., 10.,  6.,  7.],
        [ 1.,  2.,  3.,  4., 10.,  6.,  7.],
        [ 1.,  2.,  3.,  4., 10.,  6.,  7.],
        [ 1.,  2.,  3.,  4., 10.,  6.,  7.]])

In [109]:
# same as vstack function
x_vstacked = torch.vstack([x, x, x, x])
x_vstacked

tensor([[ 1.,  2.,  3.,  4., 10.,  6.,  7.],
        [ 1.,  2.,  3.,  4., 10.,  6.,  7.],
        [ 1.,  2.,  3.,  4., 10.,  6.,  7.],
        [ 1.,  2.,  3.,  4., 10.,  6.,  7.]])

In [121]:
x_hstacked = torch.stack([x, x, x, x], dim=1)
x_hstacked.shape

torch.Size([7, 4])

In [119]:
# Same as hstack?? - not really
x_hstacked = torch.hstack((x, x, x, x))
x_hstacked.shape

torch.Size([28])

* torch.stack(..., dim=1) creates a new dimension and places the input tensors along it.

* torch.hstack(...) for 1D tensors, concatenates them into a single longer 1D tensor.

In [125]:
# Squeeze
y = torch.rand(size=(8,1))
print(f'Shape before squeeze: {y.shape}')
y = y.squeeze()
print(f'Shape after squeeze: {y.shape}')


Shape before squeeze: torch.Size([8, 1])
Shape after squeeze: torch.Size([8])


In [126]:
# Unsqueeze
y_unsqueezed = y.unsqueeze(dim=0)
print(f'Shape after unsqueeze: {y_unsqueezed.shape}')

Shape after unsqueeze: torch.Size([1, 8])


In [127]:
y_unsqueezed = y.unsqueeze(dim=1) # Different dim
print(f'Shape after unsqueeze: {y_unsqueezed.shape}')

Shape after unsqueeze: torch.Size([8, 1])


In [134]:
# Permute - fancy word for rearrange
x = torch.rand(size=(10, 20, 3))
x_permuted = x.permute(2, 0, 1)
print(f'Shape before permute: {x.shape}')
print(f'Shape after permute: {x_permuted.shape}') # Keep in mind - x_permuted is a view of x - so changes to permuted will affect x

Shape before permute: torch.Size([10, 20, 3])
Shape after permute: torch.Size([3, 10, 20])


In this case, the original tensor x has shape (10, 20, 3). By calling x.permute(2, 0, 1), you are telling PyTorch to put the dimension at index 2 (size 3) at the first position (index 0), the dimension at index 0 (size 10) at the second position (index 1), and the dimension at index 1 (size 20) at the third position (index 2). This results in a new shape of (3, 10, 20).





### Indexing

In [136]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [138]:
x[0], x[0].shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [139]:
# Now on middle bracket (dim=1)
x[0][0], x[0][0].shape

(tensor([1, 2, 3]), torch.Size([3]))

In [140]:
# dim=2
x[0][0][0]

tensor(1)

In [142]:
x[0,0,0] # Same

tensor(1)

#### Slicing

In [144]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [145]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [146]:
x[0,:,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [147]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [149]:
x[:,0,:].squeeze()

tensor([1, 2, 3])

In [154]:
x[0][:][1:]

tensor([[4, 5, 6],
        [7, 8, 9]])

### PyTorch and NumPy

In [156]:
array = np.arange(1,20, dtype=np.float32)
array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float32)

In [161]:
tensor = torch.from_numpy(array)
tensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19.])

In [163]:
# Changes to numpy array doesn't affect tensor
array = array + 2
array, tensor

(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
        18., 19., 20., 21., 22., 23.], dtype=float32),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19.]))

In [164]:
numpy_tensor = tensor.numpy()
numpy_tensor

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float32)

In [165]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
