<a href="https://colab.research.google.com/github/Maniacravi/pytorch-deep-learning/blob/main/00_pytorch_fundamentals_mani.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

My code along for the first section

## Import statements


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Tensors

### Intro

#### Scalars

In [2]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

9

In [5]:
scalar.shape

torch.Size([])

#### Vectors

In [6]:
vector = torch.tensor([9, 9, 9])
vector

tensor([9, 9, 9])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

#### MATRIX

In [9]:
MATRIX = torch.tensor([[9, 9],
                       [10, 11]])
MATRIX

tensor([[ 9,  9],
        [10, 11]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# slicing

MATRIX[0]

tensor([9, 9])

In [13]:
MATRIX[1, 0]

tensor(10)

#### TENSOR

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Creating Tensors

#### Random Tensors

Creating random tensors because they are the most usual way to create tensors in code

In [27]:
# Create a random tensor

random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.5634, 0.0523, 0.0011, 0.1825],
        [0.2674, 0.8673, 0.2341, 0.0161],
        [0.0299, 0.1540, 0.9526, 0.9091]])

In [19]:
random_tensor.shape

torch.Size([3, 4, 6])

In [20]:
random_tensor.ndim

3

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor, random_image_size_tensor.ndim, random_image_size_tensor.shape

(tensor([[[0.6763, 0.8986, 0.0291,  ..., 0.3638, 0.4245, 0.2210],
          [0.4569, 0.9883, 0.9402,  ..., 0.3334, 0.0104, 0.4459],
          [0.8517, 0.6790, 0.8334,  ..., 0.4194, 0.8088, 0.4164],
          ...,
          [0.5148, 0.9991, 0.8305,  ..., 0.1391, 0.7130, 0.7386],
          [0.8243, 0.9806, 0.4165,  ..., 0.8762, 0.3138, 0.4268],
          [0.0014, 0.4376, 0.7164,  ..., 0.8895, 0.8005, 0.6523]],
 
         [[0.8994, 0.2043, 0.3196,  ..., 0.9814, 0.1752, 0.1710],
          [0.7753, 0.1107, 0.0546,  ..., 0.6809, 0.6535, 0.7321],
          [0.4655, 0.9326, 0.4491,  ..., 0.8731, 0.6571, 0.5260],
          ...,
          [0.1811, 0.0299, 0.0948,  ..., 0.2943, 0.6694, 0.5973],
          [0.2277, 0.2890, 0.6889,  ..., 0.1274, 0.9975, 0.5521],
          [0.3556, 0.0566, 0.2336,  ..., 0.3565, 0.2408, 0.5647]],
 
         [[0.7334, 0.2408, 0.6974,  ..., 0.6584, 0.2214, 0.2447],
          [0.0364, 0.3451, 0.2567,  ..., 0.2909, 0.0730, 0.0357],
          [0.1354, 0.3560, 0.4792,  ...,

In [24]:
# Create a random tensor again
random_tensor_2 = torch.rand(size=(3, 1920, 1080))
random_tensor_2.shape

torch.Size([3, 1920, 1080])

#### Zeros and Ones

In [25]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# All ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype # Explore the datatype of the tensor

torch.float32

#### Creating a Range of tensors and tensors-like

In [35]:
# torch.range
torch.range(0,10) # Deprecated

<ipython-input-35-462832172>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# also can use step
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [40]:
# Create tensors like
ten_zeros = torch.zeros_like(input = one_to_ten) # Returns a tensor filled with the scalar value 0, with the same size as input
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [41]:
# Float_32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None) # What datatype is the tensor


In [42]:
float_32_tensor.dtype

torch.float32

Even when dtype is specified as None - still produces a float32 tensor

In [43]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor
                               device=None, # What device is your tensor on ('cpu', 'gpu' etc)
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

** Note ** : Learn about tensor datatypes and their differences. May run into errors with this often

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16) # Crearting a float16 tensor from the float32 tensor
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

This works surprisignly but beware of mixing multiple types of tensors. Sometimes will raise errors

In [47]:
int_32_tensor = float_32_tensor.type(dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [48]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

Still works

#### Getting info from Tensors

In [49]:
# Get dtype
int_32_tensor.dtype

torch.int32

In [50]:
# Get shape
float_32_tensor.shape

torch.Size([3])

In [51]:
# Get device
float_16_tensor.device

device(type='cpu')

In [52]:
# Get ndim
int_32_tensor.ndim

1

#### Manipulating Tensors (tensor operations)

Includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Mat Mult

In [53]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [54]:
# Add two tensors
int_32_tensor + float_32_tensor

tensor([ 6., 12., 18.])

In [55]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [56]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [59]:
# Torch inbuilt functions
torch.mul(tensor, 10), torch.add(tensor, 10), torch.sub(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]), tensor([-9, -8, -7]))

In [64]:
# Mat mult
torch.matmul(float_32_tensor, tensor.type(torch.float32))

tensor(42.)

In [68]:
# Another one
torch.matmul(torch.rand(size=(4,4)), torch.rand(size=(4,1)))

tensor([[0.9462],
        [1.0132],
        [1.3153],
        [0.6183]])

In [71]:
# Do the matmul by forloop and see how long the time difference is
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value


CPU times: user 856 µs, sys: 1 ms, total: 1.86 ms
Wall time: 1.57 ms


tensor(14)

In [72]:
# same using matmul
%%time
torch.matmul(tensor, tensor) # Vectorized version - therefore much faster


CPU times: user 537 µs, sys: 0 ns, total: 537 µs
Wall time: 381 µs


tensor(14)