<a href="https://colab.research.google.com/github/Maniacravi/pytorch-deep-learning/blob/main/00_pytorch_fundamentals_mani.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

My code along for the first section

## Import statements


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Tensors

### Intro

#### Scalars

In [15]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [13]:
scalar.ndim

0

In [25]:
# Get tensor back as Python int
scalar.item()

9

In [26]:
scalar.shape

torch.Size([])

#### Vectors

In [30]:
vector = torch.tensor([9, 9, 9])
vector

tensor([9, 9, 9])

In [31]:
vector.ndim

1

In [32]:
vector.shape

torch.Size([3])

#### MATRIX

In [34]:
MATRIX = torch.tensor([[9, 9],
                       [10, 11]])
MATRIX

tensor([[ 9,  9],
        [10, 11]])

In [28]:
MATRIX.ndim

2

In [29]:
MATRIX.shape

torch.Size([2, 2])

In [35]:
# slicing

MATRIX[0]

tensor([9, 9])

In [39]:
MATRIX[1, 0]

tensor(10)

#### TENSOR

In [54]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [55]:
TENSOR.ndim

3

In [56]:
TENSOR.shape

torch.Size([1, 3, 3])

In [53]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Creating Tensors

#### Random Tensors

Creating random tensors because they are the most usual way to create tensors in code

In [60]:
# Create a random tensor

random_tensor = torch.rand(3, 4, 6)
random_tensor


tensor([[[2.8774e-01, 1.6719e-01, 2.1923e-01, 4.5158e-01, 1.5019e-01,
          1.3369e-01],
         [7.6795e-01, 4.8574e-02, 9.6945e-01, 6.0431e-01, 9.8641e-01,
          1.4909e-01],
         [8.8706e-02, 3.9097e-01, 9.0002e-01, 8.7881e-01, 4.3701e-01,
          3.5007e-01],
         [7.1766e-01, 9.6372e-01, 3.6624e-01, 7.7079e-01, 8.2822e-01,
          4.6814e-02]],

        [[5.2748e-01, 4.4555e-01, 9.1015e-01, 9.5338e-01, 4.7744e-01,
          4.1752e-01],
         [9.8843e-01, 3.2321e-01, 9.8473e-01, 5.0751e-01, 8.1749e-01,
          9.2989e-01],
         [7.1118e-01, 1.7821e-01, 2.0323e-01, 1.1992e-04, 4.5049e-01,
          1.9435e-01],
         [7.7049e-01, 2.8943e-01, 6.7728e-01, 8.7415e-01, 4.1273e-01,
          5.1393e-01]],

        [[4.4091e-01, 1.1703e-01, 9.7336e-01, 8.1648e-01, 8.2113e-01,
          1.1825e-01],
         [5.9717e-01, 1.1994e-01, 9.4069e-02, 8.2299e-01, 4.5935e-01,
          8.5222e-01],
         [4.0503e-01, 7.7352e-01, 9.9674e-01, 3.9497e-01, 4.3318e-

In [61]:
random_tensor.shape

torch.Size([3, 4, 6])

In [62]:
random_tensor.ndim

3

In [63]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor, random_image_size_tensor.ndim, random_image_size_tensor.shape

(tensor([[[0.2755, 0.7464, 0.5414,  ..., 0.7973, 0.3066, 0.1936],
          [0.6242, 0.4711, 0.3111,  ..., 0.9536, 0.1857, 0.6061],
          [0.3341, 0.4377, 0.6689,  ..., 0.3231, 0.1986, 0.0646],
          ...,
          [0.1357, 0.8462, 0.4808,  ..., 0.0619, 0.9814, 0.3210],
          [0.5182, 0.6066, 0.4034,  ..., 0.6569, 0.9959, 0.4799],
          [0.8263, 0.9385, 0.3616,  ..., 0.0369, 0.0376, 0.0655]],
 
         [[0.4190, 0.1445, 0.5795,  ..., 0.5002, 0.5488, 0.8467],
          [0.0213, 0.1895, 0.0267,  ..., 0.5300, 0.2134, 0.4193],
          [0.4403, 0.6729, 0.2818,  ..., 0.4198, 0.3754, 0.5531],
          ...,
          [0.4972, 0.0307, 0.9024,  ..., 0.8657, 0.9107, 0.9825],
          [0.0391, 0.7426, 0.7751,  ..., 0.8796, 0.2993, 0.4701],
          [0.7257, 0.6989, 0.9155,  ..., 0.4227, 0.0537, 0.9670]],
 
         [[0.5035, 0.4648, 0.3462,  ..., 0.5413, 0.7633, 0.1079],
          [0.8394, 0.2025, 0.9726,  ..., 0.3550, 0.1064, 0.0557],
          [0.5802, 0.1700, 0.5836,  ...,