<a href="https://colab.research.google.com/github/Maniacravi/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(size=(7,7))
tensor

tensor([[0.3307, 0.7716, 0.7523, 0.3917, 0.8319, 0.9864, 0.3657],
        [0.7871, 0.1800, 0.4615, 0.0594, 0.9398, 0.1602, 0.8589],
        [0.5980, 0.2664, 0.7477, 0.6290, 0.6990, 0.9474, 0.3280],
        [0.6532, 0.7902, 0.9861, 0.7774, 0.6165, 0.0216, 0.9597],
        [0.4410, 0.8561, 0.8783, 0.6310, 0.9863, 0.9365, 0.5572],
        [0.3393, 0.2580, 0.3337, 0.5922, 0.3685, 0.3080, 0.5451],
        [0.8376, 0.0279, 0.5903, 0.4310, 0.5261, 0.7170, 0.5558]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor_2 = torch.rand(size=(1,7))

# Perform matrix multiplication
mult_tensor = torch.mm(tensor, tensor_2.T)
mult_tensor

tensor([[2.3541],
        [1.6700],
        [2.2599],
        [2.3114],
        [2.7113],
        [1.3512],
        [2.0111]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand(size=(7,7))
tensor_2 = torch.rand(size=(1,7))

# Matrix multiply tensors
tensor_mult = torch.mm(tensor_1, tensor_2.T)
tensor_mult, tensor_mult.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)
# torch.cuda.manual_seed(1234)
# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
tensor_1 = torch.rand(size=(2,3)).to('cuda')
tensor_2 = torch.rand(size=(2,3)).to('cuda')
tensor_1, tensor_2


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
mm_tensor = torch.mm(tensor_1, tensor_2.T)
mm_tensor, mm_tensor.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
mm_tensor.max()
# Find min
mm_tensor.min()


tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
mm_tensor.argmax()

# Find arg min
mm_tensor.argmin()

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [20]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(size=(1,1,1,10))

# Remove single dimensions
flattened_tensor = random_tensor.flatten()
squeezed_tensor = random_tensor.squeeze() # In this case both are same - but use squeeze

# Print out tensors and their shapes
random_tensor, random_tensor.shape, flattened_tensor, flattened_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

In [22]:
flattened_tensor == squeezed_tensor, flattened_tensor.shape == squeezed_tensor.shape

(tensor([True, True, True, True, True, True, True, True, True, True]), True)